const CURRENCY_SYMBOL_MAP: Record<string, string> = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  JPY: '¥',
  CNY: '¥',
  KRW: '₩',
  INR: '₹',
  RUB: '₽',
  BRL: 'R$',
  PLN: 'zł',
  TRY: '₺',
  UAH: '₴',
  VND: '₫',
  THB: '฿',
  PHP: '₱',
  IDR: 'Rp',
  MYR: 'RM',
  SGD: 'S$',
  HKD: 'HK$',
  TWD: 'NT$',
  AUD: 'A$',
  CAD: 'C$',
  NZD: 'NZ$',
  CHF: 'CHF',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  CZK: 'Kč',
  HUF: 'Ft',
  RON: 'lei',
  ILS: '₪',
  AED: 'AED',
  SAR: 'SAR',
  ZAR: 'R',
  MXN: 'MX$',
  ARS: 'ARS$',
  CLP: 'CLP$',
  COP: 'COP$',
  PKR: '₨',
  BDT: '৳',
  NGN: '₦',
  KES: 'KSh',
  LKR: 'Rs',
  NPR: 'Rs',
};

export function defaultCurrencySymbol(currencyCode: string): string {
  const code = String(currencyCode ?? '').trim().toUpperCase();
  return CURRENCY_SYMBOL_MAP[code] ?? (code || '$');
}
