/** Bootstrap rows for `region_country_configs` — covers Flutter RegionConfig.allRegions + common storefronts. */
export type RegionCountrySeed = {
  countryCode: string;
  countryName: string;
  nativeName?: string;
  steamCc: string;
  defaultCurrency: string;
  currencySymbol?: string;
  steamLanguage: string;
  sortOrder: number;
};

export const REGION_COUNTRY_DEFAULTS: RegionCountrySeed[] = [
  { countryCode: 'US', countryName: 'United States', steamCc: 'US', defaultCurrency: 'USD', steamLanguage: 'en', sortOrder: 10 },
  { countryCode: 'GB', countryName: 'United Kingdom', steamCc: 'GB', defaultCurrency: 'GBP', steamLanguage: 'en', sortOrder: 20 },
  { countryCode: 'CA', countryName: 'Canada', steamCc: 'CA', defaultCurrency: 'CAD', steamLanguage: 'en', sortOrder: 30 },
  { countryCode: 'AU', countryName: 'Australia', steamCc: 'AU', defaultCurrency: 'AUD', steamLanguage: 'en', sortOrder: 40 },
  { countryCode: 'IN', countryName: 'India', steamCc: 'IN', defaultCurrency: 'INR', steamLanguage: 'en', sortOrder: 50 },
  { countryCode: 'DE', countryName: 'Germany', nativeName: 'Deutschland', steamCc: 'DE', defaultCurrency: 'EUR', steamLanguage: 'de', sortOrder: 60 },
  { countryCode: 'FR', countryName: 'France', steamCc: 'FR', defaultCurrency: 'EUR', steamLanguage: 'fr', sortOrder: 70 },
  { countryCode: 'JP', countryName: 'Japan', nativeName: '日本', steamCc: 'JP', defaultCurrency: 'JPY', steamLanguage: 'ja', sortOrder: 80 },
  { countryCode: 'KR', countryName: 'South Korea', nativeName: '한국', steamCc: 'KR', defaultCurrency: 'KRW', steamLanguage: 'ko', sortOrder: 90 },
  { countryCode: 'CN', countryName: 'China', nativeName: '中国', steamCc: 'CN', defaultCurrency: 'CNY', steamLanguage: 'zh', sortOrder: 100 },
  { countryCode: 'BR', countryName: 'Brazil', nativeName: 'Brasil', steamCc: 'BR', defaultCurrency: 'BRL', steamLanguage: 'pt', sortOrder: 110 },
  { countryCode: 'PL', countryName: 'Poland', nativeName: 'Polska', steamCc: 'PL', defaultCurrency: 'PLN', steamLanguage: 'pl', sortOrder: 120 },
  { countryCode: 'RU', countryName: 'Russia', nativeName: 'Россия', steamCc: 'RU', defaultCurrency: 'RUB', steamLanguage: 'ru', sortOrder: 130 },
  { countryCode: 'ES', countryName: 'Spain', nativeName: 'España', steamCc: 'ES', defaultCurrency: 'EUR', steamLanguage: 'es', sortOrder: 140 },
  { countryCode: 'IT', countryName: 'Italy', nativeName: 'Italia', steamCc: 'IT', defaultCurrency: 'EUR', steamLanguage: 'it', sortOrder: 150 },
  { countryCode: 'NL', countryName: 'Netherlands', nativeName: 'Nederland', steamCc: 'NL', defaultCurrency: 'EUR', steamLanguage: 'nl', sortOrder: 160 },
  { countryCode: 'SE', countryName: 'Sweden', steamCc: 'SE', defaultCurrency: 'SEK', steamLanguage: 'sv', sortOrder: 170 },
  { countryCode: 'NO', countryName: 'Norway', steamCc: 'NO', defaultCurrency: 'NOK', steamLanguage: 'no', sortOrder: 180 },
  { countryCode: 'DK', countryName: 'Denmark', steamCc: 'DK', defaultCurrency: 'DKK', steamLanguage: 'da', sortOrder: 190 },
  { countryCode: 'FI', countryName: 'Finland', steamCc: 'FI', defaultCurrency: 'EUR', steamLanguage: 'fi', sortOrder: 200 },
  { countryCode: 'MX', countryName: 'Mexico', steamCc: 'MX', defaultCurrency: 'MXN', steamLanguage: 'es', sortOrder: 210 },
  { countryCode: 'AR', countryName: 'Argentina', steamCc: 'AR', defaultCurrency: 'ARS', steamLanguage: 'es', sortOrder: 220 },
  { countryCode: 'CL', countryName: 'Chile', steamCc: 'CL', defaultCurrency: 'CLP', steamLanguage: 'es', sortOrder: 230 },
  { countryCode: 'CO', countryName: 'Colombia', steamCc: 'CO', defaultCurrency: 'COP', steamLanguage: 'es', sortOrder: 240 },
  { countryCode: 'TW', countryName: 'Taiwan', steamCc: 'TW', defaultCurrency: 'TWD', steamLanguage: 'zh', sortOrder: 250 },
  { countryCode: 'HK', countryName: 'Hong Kong', steamCc: 'HK', defaultCurrency: 'HKD', steamLanguage: 'en', sortOrder: 260 },
  { countryCode: 'SG', countryName: 'Singapore', steamCc: 'SG', defaultCurrency: 'SGD', steamLanguage: 'en', sortOrder: 270 },
  { countryCode: 'NZ', countryName: 'New Zealand', steamCc: 'NZ', defaultCurrency: 'NZD', steamLanguage: 'en', sortOrder: 280 },
  { countryCode: 'ZA', countryName: 'South Africa', steamCc: 'ZA', defaultCurrency: 'ZAR', steamLanguage: 'en', sortOrder: 290 },
  { countryCode: 'TR', countryName: 'Turkey', nativeName: 'Türkiye', steamCc: 'TR', defaultCurrency: 'TRY', steamLanguage: 'tr', sortOrder: 300 },
  { countryCode: 'SA', countryName: 'Saudi Arabia', steamCc: 'SA', defaultCurrency: 'SAR', steamLanguage: 'ar', sortOrder: 310 },
  { countryCode: 'AE', countryName: 'United Arab Emirates', steamCc: 'AE', defaultCurrency: 'AED', steamLanguage: 'ar', sortOrder: 320 },
  { countryCode: 'ID', countryName: 'Indonesia', steamCc: 'ID', defaultCurrency: 'IDR', steamLanguage: 'id', sortOrder: 330 },
  { countryCode: 'TH', countryName: 'Thailand', steamCc: 'TH', defaultCurrency: 'THB', steamLanguage: 'th', sortOrder: 340 },
  { countryCode: 'VN', countryName: 'Vietnam', steamCc: 'VN', defaultCurrency: 'VND', steamLanguage: 'vi', sortOrder: 350 },
  { countryCode: 'PH', countryName: 'Philippines', steamCc: 'PH', defaultCurrency: 'PHP', steamLanguage: 'en', sortOrder: 360 },
  { countryCode: 'MY', countryName: 'Malaysia', steamCc: 'MY', defaultCurrency: 'MYR', steamLanguage: 'en', sortOrder: 370 },
  { countryCode: 'UA', countryName: 'Ukraine', steamCc: 'UA', defaultCurrency: 'UAH', steamLanguage: 'uk', sortOrder: 380 },
  { countryCode: 'CH', countryName: 'Switzerland', steamCc: 'CH', defaultCurrency: 'CHF', steamLanguage: 'de', sortOrder: 390 },
  { countryCode: 'AT', countryName: 'Austria', steamCc: 'AT', defaultCurrency: 'EUR', steamLanguage: 'de', sortOrder: 400 },
  { countryCode: 'BE', countryName: 'Belgium', steamCc: 'BE', defaultCurrency: 'EUR', steamLanguage: 'fr', sortOrder: 410 },
  { countryCode: 'PT', countryName: 'Portugal', steamCc: 'PT', defaultCurrency: 'EUR', steamLanguage: 'pt', sortOrder: 420 },
  { countryCode: 'CZ', countryName: 'Czech Republic', steamCc: 'CZ', defaultCurrency: 'CZK', steamLanguage: 'cs', sortOrder: 430 },
  { countryCode: 'HU', countryName: 'Hungary', steamCc: 'HU', defaultCurrency: 'HUF', steamLanguage: 'hu', sortOrder: 440 },
  { countryCode: 'RO', countryName: 'Romania', steamCc: 'RO', defaultCurrency: 'RON', steamLanguage: 'ro', sortOrder: 450 },
  { countryCode: 'IL', countryName: 'Israel', steamCc: 'IL', defaultCurrency: 'ILS', steamLanguage: 'he', sortOrder: 460 },
  { countryCode: 'GR', countryName: 'Greece', steamCc: 'GR', defaultCurrency: 'EUR', steamLanguage: 'el', sortOrder: 470 },
  { countryCode: 'IE', countryName: 'Ireland', steamCc: 'IE', defaultCurrency: 'EUR', steamLanguage: 'en', sortOrder: 480 },
  { countryCode: 'NG', countryName: 'Nigeria', steamCc: 'NG', defaultCurrency: 'NGN', steamLanguage: 'en', sortOrder: 490 },
  { countryCode: 'PK', countryName: 'Pakistan', steamCc: 'PK', defaultCurrency: 'PKR', steamLanguage: 'en', sortOrder: 500 },
  { countryCode: 'BD', countryName: 'Bangladesh', steamCc: 'BD', defaultCurrency: 'BDT', steamLanguage: 'en', sortOrder: 510 },
  { countryCode: 'KE', countryName: 'Kenya', steamCc: 'KE', defaultCurrency: 'KES', steamLanguage: 'en', sortOrder: 520 },
  { countryCode: 'LK', countryName: 'Sri Lanka', steamCc: 'LK', defaultCurrency: 'LKR', steamLanguage: 'en', sortOrder: 530 },
  { countryCode: 'NP', countryName: 'Nepal', steamCc: 'NP', defaultCurrency: 'NPR', steamLanguage: 'en', sortOrder: 540 },
  { countryCode: 'GH', countryName: 'Ghana', steamCc: 'GH', defaultCurrency: 'GHS', steamLanguage: 'en', sortOrder: 550 },
  { countryCode: 'TZ', countryName: 'Tanzania', steamCc: 'TZ', defaultCurrency: 'TZS', steamLanguage: 'en', sortOrder: 560 },
  { countryCode: 'UG', countryName: 'Uganda', steamCc: 'UG', defaultCurrency: 'UGX', steamLanguage: 'en', sortOrder: 570 },
  { countryCode: 'JM', countryName: 'Jamaica', steamCc: 'JM', defaultCurrency: 'USD', steamLanguage: 'en', sortOrder: 580 },
  { countryCode: 'TT', countryName: 'Trinidad and Tobago', steamCc: 'TT', defaultCurrency: 'USD', steamLanguage: 'en', sortOrder: 590 },
  { countryCode: 'MT', countryName: 'Malta', steamCc: 'MT', defaultCurrency: 'EUR', steamLanguage: 'en', sortOrder: 600 },
  { countryCode: 'CY', countryName: 'Cyprus', steamCc: 'CY', defaultCurrency: 'EUR', steamLanguage: 'en', sortOrder: 610 },
  { countryCode: 'ZW', countryName: 'Zimbabwe', steamCc: 'ZW', defaultCurrency: 'USD', steamLanguage: 'en', sortOrder: 620 },
  { countryCode: 'MU', countryName: 'Mauritius', steamCc: 'MU', defaultCurrency: 'MUR', steamLanguage: 'en', sortOrder: 630 },
  { countryCode: 'BZ', countryName: 'Belize', steamCc: 'BZ', defaultCurrency: 'USD', steamLanguage: 'en', sortOrder: 640 },
  { countryCode: 'GY', countryName: 'Guyana', steamCc: 'GY', defaultCurrency: 'USD', steamLanguage: 'en', sortOrder: 650 },
  { countryCode: 'ET', countryName: 'Ethiopia', steamCc: 'ET', defaultCurrency: 'ETB', steamLanguage: 'en', sortOrder: 660 },
  { countryCode: 'BW', countryName: 'Botswana', steamCc: 'BW', defaultCurrency: 'BWP', steamLanguage: 'en', sortOrder: 670 },
];
